### ISSUE TITLE
Node.js kernel text output and new line issues

### ISSUE THREAD

**Issue by RandomFractals** [DonJayamanne/typescript-notebook#60]
When using `fs.readFileSync` with `utf-8` encoding, Node.js kernel outputs odd text data, especially around new lines with some escape characters:

![typescript-notebook-text-output](https://user-images.githubusercontent.com/656833/162761953-9d763eb4-d6ad-4576-8edb-2c65acca693a.png)

Which results in the following data table display:

![image](https://user-images.githubusercontent.com/656833/162763953-ab807c5b-f237-4d48-9822-67b109affe00.png)

Expected: 

Raw plain text CSV content of this data file: https://raw.githubusercontent.com/RandomFractals/vscode-data-table/main/data/usa-airports.csv

The same happens for JSON string: https://github.com/RandomFractals/vscode-data-table/blob/main/data/usa-airports.json

![image](https://user-images.githubusercontent.com/656833/162762917-1648ced6-2c6e-4af8-b5f2-0411c5b3a366.png)

**Comment by RandomFractals** [comment]
I resolved it by using `display.text(string)` method, but I expected string vars to be outputted without concat or any escape characters as above. This works for now:

![image](https://user-images.githubusercontent.com/656833/162768221-1de2a174-f520-4756-bf46-7d2cb2830566.png)

**Comment by DonJayamanne** [comment]
`console.log(` or the like would resolve this.
Basically if you just dump a raw string, its the same as dumping output into a shell and the output is formatted by the shell to escape ansi codes.
And VS Codes renderer supports ANSI codes hence you get a green output, but when you open it as a plain text output due to the large content, then VS Code doesn't escape any of that output.

If you would like a change in that behavior please file an issue in VSCode as thats beyond the control of this extension.
